### ISSUE TITLE
年間スケジュールを削除して，Google Calenderを載せよう

### ISSUE THREAD

**Issue by tayoon** [Kenny-NISLab/niswiki#163]
- [ ]

**Comment by RyoichiNakai** [comment]
- [ ] Googleカレンダーの使い方を説明するページを作成

**Comment by RyoichiNakai** [comment]
#169 と同じIssueです．

**Comment by RyoichiNakai** [comment]
- content/newB4をcontent/new-b4に変更
- content/new-b4/_index.mdの中の「コミニケーションツールについて」の見出しの中の「Slackの使い方」のリンクをURLではなく絶対パスに変更
- 「論文関連（卒論・修論含む）」の中に「修論諮問会・卒論発表会注意事項」を追加

**Comment by tayoon** [comment]
Googleカレンダー設定のGoogleカレンダーのURL変更
