### ISSUE TITLE
裁断のやり方

### ISSUE THREAD

**Issue by Howellm** [Kenny-NISLab/niswiki#175]
## What feature
- [x] 裁断のやり方を 運営管理 > 物品班 > 物品購入の取り扱い　に記載

**Comment by kogepanh** [comment]
@Howellm @tayoon 
追加・編集完了してるよな？
Closeするんで、必要やったらReOpenしてください！

**Comment by Howellm** [comment]
裁断の詳細の追加
- [ ] 書籍のカバー取る旨を記載
- [ ] 裁断機は両手で押して切り取る(片手ではダメな理由を添えて)旨を記載
- [ ] サイドバーをもう少し簡潔に
- [ ] スキャンする際の両面原稿の操作画面の追加
