### ISSUE TITLE
卒業生一覧の記載ミス

### ISSUE THREAD

**Issue by Riki-Okunishi** [Kenny-NISLab/niswiki#284]
- [x] 記載ミスの修正

[卒業生・就職先一覧](https://wiki.nislab.io/members/)に一部記載ミスがある．

## 記載ミス一覧
+ 2018～2020年度
  + 生駒さんは「Daishiro Ikoma」
+ 2014～2016年度
  + 石正さんの英語表記が姓名逆
+ 2014年度
  + 脇田さんは「Aruto Wakita」
+ 2008年度
  + 門脇さんは「Kohei Kadowaki」

**Comment by kogepanh** [comment]
報告ありがとう！
修正してPR更新しときます！
