### ISSUE TITLE
URLの修正

### ISSUE THREAD

**Issue by shinnosuke-K** [Kenny-NISLab/niswiki#78]
- リンクのURLが直接記事までのリンクではないやつがあったから修正します

**Comment by shinnosuke-K** [comment]
URLベタ書きではなくて、サイト名にリンクを貼る形にもやっておく（見にくいから）

**Comment by kogepanh** [comment]
ありがとうございます！
やばいバグとかでなければ、リファクタ系はだいたいで大丈夫です！
gitの練習も兼ねて、勉強したいって言ってた人たちにやってもらおうかと思ってます！

**Comment by shinnosuke-K** [comment]
了解
今やっているところだけにしておくわ
