### ISSUE TITLE
フォントのデカさ

### ISSUE THREAD

**Issue by shinnosuke-K** [Kenny-NISLab/niswiki#80]
ところどころフォントの大きさが不自然やからいい感じにやってほしい

**Comment by kogepanh** [comment]
了解です！
Headingがやたらデカイとかってことですよね？

**Comment by shinnosuke-K** [comment]
あと本文が小さいかも

**Comment by kogepanh** [comment]
了解です！
簡単やと思うんで、あえて作業残しといて誰かにやってもらえてらやってもらいます！笑
