### ISSUE TITLE
VSCodeでのCloud LaTeXの作業方法

### ISSUE THREAD

**Issue by shinnosuke-K** [Kenny-NISLab/niswiki#82]
Cloud LaTeXをVSCode上で作業が出来る方法があるから、必要そうなら追加してあげて

参考記事
https://prtimes.jp/main/html/rd/p/000000038.000017667.html
https://github.com/cloudlatex-team/cloudlatex-vscode-extension/blob/master/docs/README_ja.md

**Comment by kogepanh** [comment]
了解です！
Wikiの内容の精査も追って行おうと考えてますので、その際に追加しようと思います！
