### ISSUE TITLE
WindowsでヘッダーのロゴがNISLAB Wikiでなくて、NISLAB WIになる

### ISSUE THREAD

**Issue by RyoichiNakai** [Kenny-NISLab/niswiki#91]
## What bug
- WindowsのChromeでヘッダーのロゴがNISLAB WIkiでなく、NISLAB WIになってしまう
- Chromeの検証ツールで確認したところ、別のsvgを読み込んでしまっている

![image](https://user-images.githubusercontent.com/49640294/110732775-22fabf00-8268-11eb-9218-2eabbe8d3c00.png)

## ToDo
- NISLAB Wiになっている原因の調査と解決
  - AWS CloudFrontのキャッシュが問題なのかもしれない（そんなことはないかもしれない）

## Additional
- 試したこと
  - ブラウザのキャッシュを消去したが、特に変わりはなかった

**Comment by kogepanh** [comment]
おーまいがっ！
今度引き継ぎ作業等するときに検討しよか！

**Comment by kogepanh** [comment]
WindowsのChromeでSVGを表示すると起きることがあるらしい。
SVGの中身が悪いようなので、後日、Windows環境で修正します。
