### ISSUE TITLE
新B4が初めに見るページを作る

### ISSUE THREAD

**Issue by kogepanh** [Kenny-NISLab/niswiki#96]
- [ ]

**Comment by kogepanh** [comment]
Googleカレンダーへのリンク？があった方がよさそう

**Comment by kogepanh** [comment]
ミーティングでの発言ルールも書いといた方がよさそう

**Comment by kogepanh** [comment]
https://wiki.nislab.io/guidance/

を編集していきます

**Comment by tayoon** [comment]
- MTGのルール
- オンラインチームミーティングはミュート解除・カメラオン
- slackの徹底
- niswikiへの誘導
